# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MODEL_DREAM2LTE) += exynos8895-dream2lte_eur_open_10.dtb
dtb-$(CONFIG_MODEL_DREAMLTE) += exynos8895-dreamlte_eur_open_10.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
